### ISSUE TITLE
How do you add an option element as a child to a select element?

### ISSUE THREAD

**Issue by rjsteinert** [artf/grapesjs-plugin-forms#1]
Hi there - It's great to form plugins for grapejs! I'm wondering if there is a way to add option elements to select lists. I'm able to create the select element but I haven't figured out where the configuration for options goes.

**Comment by artf** [comment]
Hi @rjsteinert you should see the option configuration in 'Settings' (once the select component is selected)

**Comment by rjsteinert** [comment]
@artf Thanks for the reply. Perhaps the demo is running on some older code where the select component has a bug? I'm not seeing settings when a select component is selected.
![screen shot 2017-11-02 at 12 45 04 pm](https://user-images.githubusercontent.com/156575/32338696-e32cc060-bfcb-11e7-9c4d-d312070f83f5.png)

**Comment by artf** [comment]
@rjsteinert definitely a bug, thanks for the catch

**Comment by afotey** [comment]
Is there a way to add form elements by themselves? 

When I try to add a textarea, for example, to a completely blank canvas, nothing happens.

**Comment by artf** [comment]
@afotey Are acting like this just by design
https://github.com/artf/grapesjs-plugin-forms/blob/master/src/components.js#L191
You have to create the form and then dragging inside form elements
