### ISSUE TITLE
Bug: Contents of inputs/textarea is not stored with the component

### ISSUE THREAD

**Issue by Azerothian** [artf/grapesjs-plugin-forms#10]
Replication Steps
- Add a text input or text area
- Click on field and enter in contents
- click 'view code' and entered content is not set as the value/contents of textarea

Versions:
- grapesjs: 0.15.10
- grapesjs-preset-webpage: 0.1.11

https://codesandbox.io/embed/hardcore-noyce-4ytug?fontsize=14&hidenavigation=1&theme=dark

**Comment by artf** [comment]
I'm not sure exporting the value from inputs is the right way, but if you need it you can extend form Components
