### ISSUE TITLE
BUG: In new release all buttons are identified as inputs

### ISSUE THREAD

**Issue by mmotov** [artf/grapesjs-plugin-forms#13]
Hi @artf! I faced an issue when the button text trait is concatenated with default button text (same as here https://github.com/artf/grapesjs/issues/3205), but after upgrading form plugin to the latest version, ALL buttons are identified as inputs, and text trait is not working at all. Now it's almost useless.
Here is the demo: https://www.loom.com/share/4977c2f7e4cb4e598a1bfe71ca4cf481
grapesjs: 0.16.44
grapesjs-plugin-forms: 2.0.1

**Comment by artf** [comment]
I'd suggest updating both grapesjs and the form plugin as so far I see no issues with button components :/
