### ISSUE TITLE
Cannot to override block's category properties

### ISSUE THREAD

**Issue by abolabo** [artf/grapesjs-plugin-forms#24]
Hi.
I tried to made category of form component collapsed via pluginOpts property inside init() but i can't.

Please see this line
https://github.com/artf/grapesjs-plugin-forms/blob/d4ceea9ec299f4b87a7a130ececdf338ed1268c0/src/blocks.js#L18
Looks like i cannot to override it with
pluginOpts : {
    'grapesjs-plugin-forms': {
                    category : {
                        id: 'forms',
                        label: 'Forms',
                        open: false
                    }
                }
}

Other plugins under your github have no this issue.

Regards

**Comment by artf** [comment]
Added new options to the plugin https://github.com/artf/grapesjs-plugin-forms/releases/tag/v2.0.5
