### ISSUE TITLE
With Select box, the options in settings is only showing value, The Option text not showing

### ISSUE THREAD

**Issue by tom-codelooms** [artf/grapesjs-plugin-forms#27]
Hi Artf, 
The form is really great plugin and thanks for the great plugin.

I am getting some issues with Select box,
Could you please help me ?

The scenario is below
I dragged the Form block and dragged Select box component, I can see those options are added in the editor, but when I click on that selectbox and check the Options in Settings, I can only see 
::
1::
Instead of 
::-Select
1::Option 1

could you please guide me how to fix this?

https://grapesjs.com/demo.html here also I can see this issue

<img width="1570" alt="Screenshot 2022-01-17 at 12 19 25 AM" src="https://user-images.githubusercontent.com/94916117/149673637-f1c6f404-2235-4247-a438-57383f27ff54.png">

**Comment by artf** [comment]
Released a new version https://github.com/artf/grapesjs-plugin-forms/releases/tag/v2.0.5 with the fix
