### ISSUE TITLE
Bug: Blur on trait textfield for button

### ISSUE THREAD

**Issue by Chilli-B** [artf/grapesjs-plugin-forms#3]
Hello, I think I found an issue concerning the button component. When the button text is changed over the according trait textfield ("Text"), the field blurs after typing each letter. If you like to enter several letters, you need to click the cursor into the textfield with your mouse after each letter.

I'm using the code unchanged. It's like that even on the demo pages. Tested on Safari and Firefox.

How can this be solved?

**Comment by artf** [comment]
I'm closing this as the issue it's quite old and the bug is not reproducible with the current version (probably was some kind of old regression)
