### ISSUE TITLE
support more than just post & get

### ISSUE THREAD

**Issue by jimmywarting** [artf/grapesjs-plugin-forms#32]
Could you instead of a dropdown allow for free text input?

ps, you can instead use [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) with autocompletion for the most common ones...

**Comment by artf** [comment]
Hi @jimmywarting you can [extend components](https://grapesjs.com/docs/modules/Components.html#update-component-type) from this plugin and use your trait types if necessary :)

**Comment by integrateddigital** [comment]
usubscribe
