### ISSUE TITLE
BUG: Recent Updates to GrapesJS Type Definitions break this plugin

### ISSUE THREAD

**Issue by stljeff1** [artf/grapesjs-plugin-forms#40]
After [this commit](https://github.com/artf/grapesjs/commit/2abeebd6a60cc412b56a38801f2141928ea77714), this plugin produces an error saying 'BlockOptions" is not a property on grapesjs

I only know about this error because I am developing with the Dev Branch of GrapesJS (for testing only, not production). This error is not caused by any official releases. I just hope this gets fixed before the next release of Grapesjs. I am using grapejs-plugin-forms v 2.0.5.

**Comment by artf** [comment]
Thanks @stljeff1 yeah I'll actually rollback that change but we'll probably need to release a breaking change the day the migration to TS of all files is completed.
