### ISSUE TITLE
[bug]No ID on form elements (and possible core bug with selecting labels)

### ISSUE THREAD

**Issue by ChristianKarlsson86** [artf/grapesjs-plugin-forms#6]
Hello, I have noticed that labels do have a "for" attribute, but the elements don't have any ID attribute. Without the ID, the for doesn't do much.

On my own application, I have extended the elements to add the ID, but now there's a new issue: When I try to select a label that has been linked to an element on the canvas, the element gets selected instead (just like when clicking the label on the actual finished page). I am not sure if that issue belongs here or in Core.

Steps to reproduce:
For the first issue, you only need to look at the settings section on any Form element in the demo.

For the second issue, you need to extend the form elements with a new trait, ID.
Then set the ID on the element.
Then set the for attribute on a label to the same as the ID on the element.
Then click on the label on the canvas.

Current workaround:
Select the label using the Layers panel.

**Comment by artf** [comment]
The IDs was omitted to avoid conflicts with multiple blocks dropped in canvas, so if you need one you configure your own block.

About the second issue, it should be solved in the latest releases (the LabelComponent was added to core months ago)
