### ISSUE TITLE
[BUG] form elements can not be dragged

### ISSUE THREAD

**Issue by Sparke2** [artf/grapesjs-plugin-forms#8]
## The bug

Whenever I'm trying to drag & drop a form element (button, input, select, textarea, checkbox, radio) - nothing happens. A green line suggesting to attach an element that I'm dragging should appear but it does not happen. This elements can not be used.

"form" and "label" elements work fine.

Ubunut 18.04 
Chromium Version 77.0.3865.75 (Official Build) snap (64-bit)

Tested with Opera - the same issue there.

**Comment by artf** [comment]
Not a bug https://github.com/artf/grapesjs-plugin-forms/blob/2a49511ecff7ed00062985dffd2306d0df9c461f/src/components.js#L192
If you want form elements to be inserted outside of `<form>`s just extend and set `draggable: true`

**Comment by lbmir** [comment]
How can I change default attributes on Demo site for example?
**from**
draggable: 'form, form *', 

**to** 
draggable: true

**Comment by lbmir** [comment]
> Not a bug
> 
> https://github.com/artf/grapesjs-plugin-forms/blob/2a49511ecff7ed00062985dffd2306d0df9c461f/src/components.js#L192
> 
> 
> If you want form elements to be inserted outside of `<form>`s just extend and set `draggable: true`

How can I change default attributes on Demo site for example?
from
draggable: 'form, form *',

to
draggable: true
